package com.grabs4buisness.quiz;

public class QuestionAnswer {

    public static String[] gkQuestions = {
            "What is the capital of France?",
            "Who wrote the play 'Romeo and Juliet'?",
            "What is the largest planet in our solar system?",
            "In which year did Christopher Columbus reach the Americas?",
            "What is the chemical symbol for gold?",
            "Which gas do plants absorb from the atmosphere?",
            "Who is the author of the Harry Potter book series?",
            "What is the tallest mountain in the world?",
            "Who painted the Mona Lisa?",
            "What is the currency of Japan?",
            "Which gas is most abundant in the Earth's atmosphere?",
            "Who is known as the 'Father of Modern Physics'?",
            "Which continent is known as the 'Dark Continent'?",
            "What is the largest mammal in the world?",
            "Who wrote the famous novel '1984'?",
            "What is the chemical symbol for water?",
            "In which country is the Great Barrier Reef located?",
            "Who is the first woman to fly solo across the Atlantic Ocean?",
            "What is the national flower of Japan?",
            "Which planet is known as the 'Red Planet'?"
    };


    public static String[] gkAnswers = {
            "Paris", "William Shakespeare", "Jupiter", "1492", "Au", "Carbon dioxide (CO2)", "J.K. Rowling",
            "Mount Everest", "Leonardo da Vinci", "Japanese Yen", "Nitrogen (N2)", "Albert Einstein",
            "Africa", "Blue Whale", "George Orwell", "H2O", "Australia", "Amelia Earhart", "Chrysanthemum", "Mars"
    };
    public static String[][] gkChoices = {
            {"London", "Berlin", "Madrid", "Paris"},
            {"Charles Dickens", "Jane Austen", "George Orwell", "William Shakespeare"},
            {"Saturn", "Venus", "Jupiter", "Mars"},
            {"1620", "1776", "1865", "1492"},
            {"Ag", "Cu", "Pt", "Au"},
            {"Carbon dioxide (CO2)", "Nitrogen (N2)", "Hydrogen (H2)", "Oxygen (O2)"},
            {"George R.R. Martin", "Agatha Christie", "J.R.R. Tolkien", "J.K. Rowling"},
            {"Kangchenjunga", "Makalu", "Mount Everest", "K2"},
            {"Michelangelo", "Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci"},
            {"Korean Won", "Indian Rupee", "Chinese Yuan", "Japanese Yen"},
            {"Oxygen (O2)", "Carbon dioxide (CO2)", "Argon (Ar)", "Nitrogen (N2)"},
            {"Isaac Newton", "Albert Einstein", "Stephen Hawking", "Marie Curie"},
            {"Africa", "Australia", "Asia", "South America"},
            {"Giraffe", "African Elephant", "Hippopotamus", "Blue Whale"},
            {"George Orwell", "Aldous Huxley", "F. Scott Fitzgerald", "George Eliot"},
            {"H2O", "CO2", "H2SO4", "N2O"},
            {"India", "Brazil", "USA", "Australia"},
            {"Harriet Quimby", "Amelia Earhart", "Beryl Markham", "Amy Johnson"},
            {"Orchid", "Chrysanthemum", "Lotus", "Sakura"},
            {"Mars", "Venus", "Mercury", "Jupiter"}
    };

    public static String[] historyQuestions = {
            "Who was the first President of the United States?",
            "In which year did World War I begin?",
            "What ancient civilization built the pyramids in Egypt?",
            "Who is known for leading the Indian independence movement against British rule?",
            "What was the historical period known as the 'Renaissance' characterized by?",
            "Which famous explorer is credited with the discovery of the sea route to India?",
            "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
            "What event is often considered the beginning of the Great Depression in the United States?",
            "Who wrote the 'Communist Manifesto' with Karl Marx?",
            "What is the significance of the Magna Carta in English history?",
            "What is the name of the ship that carried the Pilgrims to North America in 1620?",
            "Who was the first female Prime Minister of India?",
            "In which year did the Berlin Wall fall, leading to the reunification of Germany?",
            "Who was the Egyptian queen who formed relationships with Julius Caesar and Mark Antony?",
            "What battle is considered the turning point in the American Civil War?",
            "Which famous civil rights leader delivered the 'I Have a Dream' speech?",
            "What ancient city was the center of the Byzantine Empire?",
            "Who is credited with inventing the printing press?",
            "What treaty officially ended World War I?",
            "What was the primary goal of the Lewis and Clark expedition?"
    };

    public static String[] historyAnswers = {
            "George Washington",
            "1914",
            "Ancient Egyptians",
            "Mahatma Gandhi",
            "Rebirth of art and learning",
            "Vasco da Gama",
            "Nikita Khrushchev",
            "Stock Market Crash of 1929",
            "Friedrich Engels",
            "Limiting the power of the king",
            "Mayflower",
            "Indira Gandhi",
            "1989",
            "Cleopatra",
            "Gettysburg",
            "Martin Luther King Jr.",
            "Constantinople",
            "Johannes Gutenberg",
            "Treaty of Versailles",
            "To explore the newly acquired Louisiana Territory"
    };

    public static String[][] historyChoices = {
            {"John Adams", "George Washington", "Thomas Jefferson", "Benjamin Franklin"},
            {"1914", "1917", "1939", "1941"},
            {"Sumerians", "Ancient Egyptians", "Greeks", "Romans"},
            {"Nelson Mandela", "Winston Churchill", "Mahatma Gandhi", "Jawaharlal Nehru"},
            {"Revolutionary political changes", "Rebirth of art and learning", "Industrialization", "Religious reform"},
            {"Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Marco Polo"},
            {"Joseph Stalin", "Nikita Khrushchev", "Mikhail Gorbachev", "Vladimir Putin"},
            {"Prohibition Era", "Wall Street Crash", "Pearl Harbor Attack", "Dust Bowl"},
            {"Karl Marx", "Friedrich Engels", "Vladimir Lenin", "Joseph Stalin"},
            {"Abolishing slavery", "Limiting the power of the king", "Establishing the British Parliament", "Ending feudalism"},
            {"Santa Maria", "Mayflower", "Endeavour", "Discovery"},
            {"Sonia Gandhi", "Indira Gandhi", "Margaret Thatcher", "Golda Meir"},
            {"1991", "1985", "1989", "1993"},
            {"Nefertiti", "Cleopatra", "Hatshepsut", "Nefertari"},
            {"Antietam", "Gettysburg", "Bull Run", "Chancellorsville"},
            {"Malcolm X", "Martin Luther King Jr.", "Nelson Mandela", "Mahatma Gandhi"},
            {"Alexandria", "Byzantium", "Athens", "Sparta"},
            {"Leonardo da Vinci", "Johannes Gutenberg", "Galileo Galilei", "Isaac Newton"},
            {"Treaty of Paris", "Treaty of Versailles", "Treaty of Tordesillas", "Treaty of Utrecht"},
            {"To establish trade routes with Asia", "To explore the Pacific Ocean", "To study native wildlife and plants", "To explore the newly acquired Louisiana Territory"}
    };


    public static String[] geographyQuestions = {
            "What is the capital of Australia?",
            "Which river is the longest in the world?",
            "In which country would you find the city of Marrakech?",
            "What is the largest desert in the world?",
            "Which mountain range runs along the border between Europe and Asia?",
            "Which continent is the largest by land area?",
            "Which country is known as the 'Land of the Rising Sun'?",
            "What is the largest ocean in the world?",
            "Which country is the southernmost point of mainland Africa?",
            "What is the capital of Canada?",
            "Which country is the smallest in terms of land area?",
            "In which ocean are the Maldives located?",
            "What is the highest mountain in North America?",
            "Which river flows through Cairo, the capital of Egypt?",
            "What is the largest island in the Mediterranean Sea?",
            "Which African country is known as the 'Rainbow Nation'?",
            "What is the capital of New Zealand?",
            "Which country is known for having the most active volcanoes?",
            "What is the world's largest rainforest?",
            "Which country is known as the 'Land of a Thousand Lakes'?"
    };

    public static String[] geographyAnswers = {
            "Canberra",
            "Nile",
            "Morocco",
            "Sahara",
            "Ural Mountains",
            "Asia",
            "Japan",
            "Pacific Ocean",
            "South Africa",
            "Ottawa",
            "Monaco",
            "Indian Ocean",
            "Denali (Mount McKinley)",
            "Nile",
            "Sicily",
            "South Africa",
            "Wellington",
            "Indonesia",
            "Amazon Rainforest",
            "Finland"
    };

    public static String[][] geographyChoices = {
            {"Canberra", "Sydney", "Melbourne", "Brisbane"},
            {"Nile", "Amazon", "Mississippi", "Yangtze"},
            {"Morocco", "Tunisia", "Algeria", "Egypt"},
            {"Sahara", "Gobi", "Arabian", "Kalahari"},
            {"Ural Mountains", "Himalayas", "Andes", "Alps"},
            {"Asia", "Africa", "North America", "South America"},
            {"China", "Japan", "Korea", "Vietnam"},
            {"Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"},
            {"South Africa", "Namibia", "Lesotho", "Zimbabwe"},
            {"Toronto", "Ottawa", "Montreal", "Vancouver"},
            {"Monaco", "San Marino", "Nauru", "Tuvalu"},
            {"Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"},
            {"Mount St. Helens", "Denali (Mount McKinley)", "Mount Logan", "Mount Kilimanjaro"},
            {"Nile", "Amazon", "Mississippi", "Yangtze"},
            {"Corsica", "Crete", "Sicily", "Cyprus"},
            {"Kenya", "South Africa", "Nigeria", "Egypt"},
            {"Wellington", "Auckland", "Christchurch", "Sydney"},
            {"Japan", "Indonesia", "Philippines", "Italy"},
            {"Amazon Rainforest", "Congo Rainforest", "Borneo Rainforest", "Atacama Desert"},
            {"Sweden", "Norway", "Iceland", "Finland"}
    };

    public static String[] mathQuestions = {
            "What is the result of 5 + 7?",
            "What is the square root of 144?",
            "Simplify: 3x + 2x - 5x",
            "What is the value of π (pi) to three decimal places?",
            "If a = 4 and b = 7, what is the value of a² + b²?",
            "Solve for x: 2x + 4 = 10",
            "What is the area of a square with a side length of 6 units?",
            "What is the product of 8 and 9?",
            "Simplify: 2/3 + 3/4",
            "If a car travels at a speed of 60 miles per hour, how far will it travel in 3 hours?",
            "What is 15% of 200?",
            "Find the missing number in the sequence: 2, 6, 10, __, 18",
            "What is the perimeter of a rectangle with length 8 units and width 5 units?",
            "What is the next prime number after 17?",
            "If a book costs $20 and is on sale for 25% off, what is the sale price?",
            "Solve for y: 2y - 5 = 7",
            "What is the value of 4! (4 factorial)?",
            "What is the largest two-digit prime number?",
            "If x + 5 = 10, what is the value of x?",
            "What is the sum of the interior angles of a triangle?"
    };

    public static String[] mathAnswers = {
            "12",
            "12",
            "0",
            "3.142",
            "65",
            "3",
            "36 square units",
            "72",
            "17/12",
            "180 miles",
            "30",
            "14",
            "26",
            "19",
            "$15",
            "6",
            "24",
            "97",
            "5",
            "180 degrees"
    };

    public static String[][] mathChoices = {
            {"10", "12", "14", "16"},
            {"9", "12", "16", "18"},
            {"-4x", "0", "4x", "6x"},
            {"3.141", "3.142", "3.143", "3.140"},
            {"41", "49", "64", "81"},
            {"x = 2", "x = 3", "x = 4", "x = 5"},
            {"12 square units", "18 square units", "24 square units", "36 square units"},
            {"64", "70", "72", "81"},
            {"5/4", "17/12", "7/5", "11/6"},
            {"120 miles", "150 miles", "180 miles", "210 miles"},
            {"30", "32", "34", "36"},
            {"14", "16", "18", "20"},
            {"18", "20", "22", "24"},
            {"17", "19", "21", "23"},
            {"$12", "$15", "$18", "$20"},
            {"3", "4", "5", "6"},
            {"12", "24", "48", "96"},
            {"89", "97", "101", "103"},
            {"3", "5", "7", "10"},
            {"90 degrees", "120 degrees", "150 degrees", "180 degrees"}
    };

    public static String[] politicsQuestions = {
            "Who is the current President of the United States?",
            "What is the term length for a U.S. Senator?",
            "In which country is the Prime Minister the head of government?",
            "What is the capital of Russia?",
            "What is the United Nations' primary mission?",
            "Which political ideology advocates for the abolition of private property?",
            "What is the largest political party in India?",
            "Who is the current Chancellor of Germany?",
            "What is the capital of Canada?",
            "Which country has the world's oldest parliament?",
            "What is the concept of 'checks and balances' in government?",
            "Who wrote 'The Communist Manifesto'?",
            "What is the highest court in the United States?",
            "Which country has a bicameral legislature known as the Diet?",
            "Who is the head of state in the United Kingdom?",
            "What is the term length for a member of the British House of Commons?",
            "What is the political system in which power is held by a single individual or family?",
            "What is the main function of the European Parliament?",
            "Which country is considered the world's largest democracy?",
            "Who is the President of the European Commission?"
    };

    public static String[] politicsAnswers = {
            "Joe Biden",
            "6 years",
            "India",
            "Moscow",
            "Promoting world peace",
            "Socialism",
            "Bharatiya Janata Party",
            "Olaf Scholz",
            "Ottawa",
            "Iceland",
            "Separation of powers",
            "Karl Marx and Friedrich Engels",
            "Supreme Court",
            "Japan",
            "Queen Elizabeth II",
            "5 years",
            "Monarchy",
            "Legislating laws",
            "India",
            "Ursula von der Leyen"
    };


    public static String[][] politicsChoices = {
            {"Joe Biden", "Donald Trump", "Barack Obama", "George W. Bush"},
            {"2 years", "4 years", "6 years", "8 years"},
            {"India", "United States", "United Kingdom", "France"},
            {"Moscow", "St. Petersburg", "Kiev", "Minsk"},
            {"Promoting world peace", "Economic development", "Environmental conservation", "Human rights advocacy"},
            {"Socialism", "Fascism", "Liberalism", "Anarchism"},
            {"Indian National Congress", "Bharatiya Janata Party", "Aam Aadmi Party", "Communist Party of India (Marxist)"},
            {"Angela Merkel", "Olaf Scholz", "Helmut Kohl", "Gerhard Schröder"},
            {"Ottawa", "Toronto", "Montreal", "Vancouver"},
            {"Iceland", "Norway", "United Kingdom", "Sweden"},
            {"Separation of powers", "Government transparency", "Political neutrality", "Social welfare programs"},
            {"Karl Marx", "Vladimir Lenin", "Mao Zedong", "Leon Trotsky"},
            {"Supreme Court", "Federal Court", "High Court", "District Court"},
            {"Japan", "China", "South Korea", "North Korea"},
            {"Queen Elizabeth II", "Boris Johnson", "Nigel Farage", "Jeremy Corbyn"},
            {"5 years", "4 years", "3 years", "6 years"},
            {"Monarchy", "Republic", "Oligarchy", "Democracy"},
            {"Legislating laws", "Representing European citizens", "Enforcing international treaties", "Judicial review"},
            {"India", "United States", "China", "Russia"},
            {"Ursula von der Leyen", "Emmanuel Macron", "Angela Merkel", "Boris Johnson"}
    };

    public static String[] musicQuestions = {
            "Who is known as the 'King of Pop'?",
            "Which instrument does Yo-Yo Ma play?",
            "Which Beatles album is often considered one of the greatest of all time?",
            "What genre of music did Elvis Presley become famous for?",
            "Which famous composer is known for his Ninth Symphony?",
            "Who sang the hit song 'Billie Jean'?",
            "What is the largest section of the orchestra?",
            "Which rock band released the album 'The Dark Side of the Moon'?",
            "What is the official national anthem of the United States?",
            "Who is the lead vocalist of the band Queen?",
            "Which music genre originated in Jamaica in the late 1960s?",
            "What famous music festival took place in 1969?",
            "Which artist is known for albums like 'Purple Haze' and 'Are You Experienced'?",
            "Who composed 'The Four Seasons'?",
            "What is the highest-pitched woodwind instrument in the orchestra?",
            "Which female artist is often referred to as the 'Queen of Pop'?",
            "What is the most widely used musical instrument in the world?",
            "Which band is famous for the song 'Stairway to Heaven'?",
            "Who wrote the opera 'The Magic Flute'?",
            "What is the primary instrument used in flamenco music?"
    };

    public static String[] musicAnswers = {
            "Michael Jackson",
            "Cello",
            "Sgt. Pepper's Lonely Hearts Club Band",
            "Rock and Roll",
            "Ludwig van Beethoven",
            "Michael Jackson",
            "Strings",
            "Pink Floyd",
            "The Star-Spangled Banner",
            "Freddie Mercury",
            "Reggae",
            "Woodstock",
            "Jimi Hendrix",
            "Antonio Vivaldi",
            "Piccolo",
            "Madonna",
            "Piano",
            "Led Zeppelin",
            "Wolfgang Amadeus Mozart",
            "Guitar"
    };

    public static String[][] musicChoices = {
            {"Elvis Presley", "Michael Jackson", "Prince", "James Brown"},
            {"Violin", "Cello", "Flute", "Trumpet"},
            {"Abbey Road", "Sgt. Pepper's Lonely Hearts Club Band", "The White Album", "Rubber Soul"},
            {"Rock and Roll", "Country", "Blues", "Jazz"},
            {"Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Ludwig van Beethoven", "Franz Schubert"},
            {"Stevie Wonder", "Michael Jackson", "Prince", "George Michael"},
            {"Brass", "Percussion", "Woodwinds", "Strings"},
            {"The Rolling Stones", "Led Zeppelin", "Pink Floyd", "The Who"},
            {"God Bless America", "The Star-Spangled Banner", "America the Beautiful", "My Country, 'Tis of Thee"},
            {"Freddie Mercury", "Mick Jagger", "Robert Plant", "Bono"},
            {"Salsa", "Reggae", "Hip-Hop", "Ska"},
            {"Monterey Pop Festival", "Coachella", "Woodstock", "Glastonbury Festival"},
            {"Jimi Hendrix", "Eric Clapton", "Jimmy Page", "Carlos Santana"},
            {"Ludwig van Beethoven", "Antonio Vivaldi", "Franz Schubert", "Wolfgang Amadeus Mozart"},
            {"Flute", "Clarinet", "Piccolo", "Oboe"},
            {"Madonna", "Whitney Houston", "Celine Dion", "Janet Jackson"},
            {"Violin", "Piano", "Guitar", "Drums"},
            {"The Rolling Stones", "Led Zeppelin", "Pink Floyd", "The Eagles"},
            {"Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Giuseppe Verdi"},
            {"Accordion", "Guitar", "Piano", "Violin"}
    };

    public static String[] csQuestions = {
            "What does 'HTML' stand for?",
            "Which programming language is often used for web development?",
            "What is the primary function of an operating system?",
            "What does 'SQL' stand for?",
            "Which data structure uses a Last-In-First-Out (LIFO) order?",
            "What is the purpose of a 'for' loop in programming?",
            "Which programming language is used for developing Android applications?",
            "What is the main function of a compiler?",
            "What is the primary purpose of an 'if' statement in programming?",
            "What does 'HTTP' stand for?",
            "What is the core component of object-oriented programming?",
            "Which protocol is used for sending email over the Internet?",
            "What does 'URL' stand for?",
            "What is the purpose of a 'function' in programming?",
            "Which programming language is commonly used for data analysis and machine learning?",
            "What is the main function of a router in a computer network?",
            "What does 'GUI' stand for?",
            "What is the term for software that is free to use, modify, and distribute?",
            "Which company developed the Java programming language?",
            "What does 'API' stand for in the context of software development?"
    };

    public static String[] csAnswers = {
            "Hypertext Markup Language",
            "JavaScript",
            "Resource management and process control",
            "Structured Query Language",
            "Stack",
            "Repeating a set of instructions a specific number of times",
            "Java",
            "Translating high-level code to machine code",
            "Conditional execution of code",
            "Hypertext Transfer Protocol",
            "Class",
            "Simple Mail Transfer Protocol (SMTP)",
            "Uniform Resource Locator",
            "Grouping a set of instructions for reuse",
            "Python",
            "Routing data between different networks",
            "Graphical User Interface",
            "Open source software",
            "Sun Microsystems",
            "Application Programming Interface"
    };

    public static String[][] csChoices = {
            {"Hypertext Markup Language", "Hyper Transfer Machine Language", "High Tech Multi Language", "Home Tool Markup Language"},
            {"JavaScript", "Python", "C++", "Ruby"},
            {"User interface design", "Game development", "Resource management and process control", "Database management"},
            {"Structured Query Language", "Simple Query Language", "System Query Language", "Sequential Query Language"},
            {"Queue", "Array", "Linked List", "Stack"},
            {"Declaring variables", "Repeating a set of instructions a specific number of times", "Executing code conditionally", "Defining classes and objects"},
            {"Python", "JavaScript", "Java", "C#"},
            {"Translating high-level code to machine code", "Debugging code", "Managing memory allocation", "Creating user interfaces"},
            {"Displaying text on the screen", "Conditional execution of code", "Managing data storage", "Iterating through a list"},
            {"Hypertext Transfer Protocol", "Hypertext Terminal Protocol", "Hyper Transfer Protocol", "High Tech Transfer Language"},
            {"Variable", "Class", "Function", "Loop"},
            {"Internet Protocol (IP)", "Simple Mail Transfer Protocol (SMTP)", "Post Office Protocol (POP)", "File Transfer Protocol (FTP)"},
            {"Uniform Resource Locator", "Universal Remote Locator", "Unified Resource Locator", "Universal Resource Language"},
            {"Grouping a set of instructions for reuse", "Displaying web pages", "Interacting with a database", "Sending emails"},
            {"Python", "Java", "C++", "R"},
            {"Routing data between different networks", "Storing data on a computer", "Translating code to binary", "Managing software updates"},
            {"Graphical User Interface", "Graphical User Input", "General User Interface", "Global User Integration"},
            {"Freeware", "Shareware", "Open source software", "Closed source software"},
            {"Microsoft", "Apple", "Sun Microsystems", "IBM"},
            {"Application Programming Interface", "Advanced Program Interface", "Automated Program Integration", "Application Program Instruction"}
    };

    public static String[] sportsQuestions = {
            "Which country won the FIFA World Cup in 2018?",
            "Who holds the record for the most home runs in Major League Baseball?",
            "In which sport is the Ryder Cup contested?",
            "Which tennis player has the most Grand Slam titles in history?",
            "What is the maximum number of players allowed on a standard soccer team?",
            "Who is often referred to as 'The Greatest' in the sport of boxing?",
            "Which country is famous for its dominance in the sport of cricket?",
            "In which year were the first modern Olympic Games held?",
            "Which athlete is known for his 'Skyhook' move in basketball?",
            "What is the term for a perfect score in a game of bowling?",
            "Which city hosted the 2016 Summer Olympics?",
            "Who is the all-time leading scorer in the NBA?",
            "What sport does the term 'birdie' belong to?",
            "Who is the fastest man in the world and holds the 100m world record?",
            "In which country did the sport of judo originate?",
            "What is the highest score one can achieve in gymnastics for a perfect routine?",
            "Which country is famous for its dominance in the sport of rugby?",
            "What is the term for winning all major championships in golf in a single calendar year?",
            "Which female tennis player is known for her powerful serve and aggressive playing style?",
            "What is the main objective in the sport of curling?"
    };

    public static String[] sportsAnswers = {
            "France",
            "Barry Bonds",
            "Golf",
            "Roger Federer",
            "11",
            "Muhammad Ali",
            "India",
            "1896",
            "Kareem Abdul-Jabbar",
            "300",
            "Rio de Janeiro",
            "Kareem Abdul-Jabbar",
            "Golf",
            "Usain Bolt",
            "Japan",
            "10",
            "New Zealand",
            "Grand Slam",
            "Serena Williams",
            "Slide stones on ice towards a target area"
    };

    public static String[][] sportsChoices = {
            {"Brazil", "Germany", "France", "Spain"},
            {"Babe Ruth", "Barry Bonds", "Hank Aaron", "Willie Mays"},
            {"Tennis", "Golf", "Cricket", "Rugby"},
            {"Serena Williams", "Rafael Nadal", "Novak Djokovic", "Roger Federer"},
            {"10", "11", "12", "13"},
            {"Mike Tyson", "Muhammad Ali", "George Foreman", "Floyd Mayweather"},
            {"Australia", "England", "India", "South Africa"},
            {"1896", "1900", "1904", "1908"},
            {"LeBron James", "Michael Jordan", "Larry Bird", "Kareem Abdul-Jabbar"},
            {"200", "250", "300", "350"},
            {"London", "Rio de Janeiro", "Tokyo", "Beijing"},
            {"Kobe Bryant", "LeBron James", "Michael Jordan", "Kareem Abdul-Jabbar"},
            {"Tennis", "Golf", "Badminton", "Table Tennis"},
            {"Carl Lewis", "Usain Bolt", "Justin Gatlin", "Asafa Powell"},
            {"China", "Japan", "South Korea", "Russia"},
            {"9", "10", "11", "12"},
            {"Australia", "England", "New Zealand", "South Africa"},
            {"Triple Crown", "Grand Slam", "Hat-trick", "Eagle"},
            {"Maria Sharapova", "Serena Williams", "Venus Williams", "Steffi Graf"},
            {"Score points by getting closest to the target"}
    };




}
